# this is the configuration file for cdata (LassoCD and randomforest)

# result_csv_file: the path of csv file for grid search results 
save_result_path: ./results/elastic_net_rf_pdata.csv

# These are for elastic net
ll1: 0.0010
ul1: 0.0090
step1: 9
ll2: 0.90
ul2: 0.99
step2: 10
random_state: 73
score_min: 10
score_max: 52

# These are for randomforest regressor
rf_params_set: {
           n_estimators: [50,100,150], 
           criterion: ["mse"],
           max_depth: [1,3,15], 
           min_samples_leaf: [1,2], 
           min_samples_split: [2], 
           max_features: ["sqrt","auto"]}