# this is the configuration file for cdata (LassoCD and randomforest)

# result_csv_file: the path of csv file for grid search results 
save_result_path: ./results/LassoCD_rf_pdata.csv

# These are for lassoCD
ll: 0.0011
ul: 0.0090
step: 80
random_state: 73
score_min: 10
score_max: 52

# These are for randomforest regressor
rf_params_set: {
           n_estimators: [150], 
           criterion: ["mse"],
           max_depth: [3], 
           min_samples_leaf: [1], 
           min_samples_split: [2], 
           max_features: ["sqrt"]}