# this is the configuration file for cdata (LassoCD and randomforest)

# result_csv_file: the path of csv file for grid search results 
save_result_path: ./results/LassoCD_rf_multi.csv

# These are for 4 randomforest regressors
rf_params_set: {
           n_estimators: [50,100,150,100], 
           criterion: ["mse","mse","mse","mse"],
           max_depth: [15,3,3,5], 
           min_samples_leaf: [1,1,1,3], 
           min_samples_split: [2,2,2,2], 
           max_features: ["sqrt","sqrt","sqrt","sqrt"]}