# this is the configuration file for cdata (LassoCD and randomforest)

# result_csv_file: the path of csv file for grid search results 
save_result_path: ./results/svmrfe_rf_rdata.csv

# These are for lassoCD
ll: 1
ul: 700
random_state: 73
score_min: 10
score_max: 52

# These are for randomforest regressor
rf_params_set: {
           n_estimators: [50], 
           criterion: ["mse"],
           max_depth: [15], 
           min_samples_leaf: [1], 
           min_samples_split: [2], 
           max_features: ["sqrt"]}